// Compiled by ClojureScript 1.10.520 {}
goog.provide('java.time');
goog.require('cljs.core');
java.time.global$module$js_joda = goog.global["JSJoda"];
java.time.Period = java.time.global$module$js_joda.Period;
java.time.Instant = java.time.global$module$js_joda.Instant;
java.time.Duration = java.time.global$module$js_joda.Duration;
java.time.LocalDate = java.time.global$module$js_joda.LocalDate;
java.time.LocalTime = java.time.global$module$js_joda.LocalTime;
java.time.ZonedDateTime = java.time.global$module$js_joda.ZonedDateTime;
java.time.LocalDateTime = java.time.global$module$js_joda.LocalDateTime;
java.time.Year = java.time.global$module$js_joda.Year;
java.time.YearMonth = java.time.global$module$js_joda.YearMonth;
java.time.ZoneId = java.time.global$module$js_joda.ZoneId;
java.time.DayOfWeek = java.time.global$module$js_joda.DayOfWeek;
java.time.Month = java.time.global$module$js_joda.Month;
java.time.Clock = java.time.global$module$js_joda.Clock;
java.time.ZoneOffset = java.time.global$module$js_joda.ZoneOffset;
java.time.OffsetDateTime = java.time.global$module$js_joda.ZonedDateTime;
java.time.OffsetTime = java.time.global$module$js_joda.LocalTime;
